### ISSUE TITLE
Identify lat-long files for georeferencing

### ISSUE THREAD

**Issue by ruckeralex** [r-b-g-b/clean-water-tool#3] opened 2019-04-03 04:28 UTC
Rucker will identify the files

**Comment by ruckeralex** [comment] 2019-04-04 05:53
Attached is a file listing public water system IDs (PWS_ID) and associated latitude and longitude for systems that are within the "Tulare Lake Basin" geographic area.  Still looking for main source file that contains ALL of the water systems.

[TulareBasin_Output.txt](https://github.com/r-b-g-b/clean-water-tool/files/3041936/TulareBasin_Output.txt)

**Comment by ruckeralex** [comment] 2019-04-09 22:38
Attached is the GIS shapefile ("EC_Summary_Apr2-19.zip").  @aaronhans, does it contain what you need for lat-long coordinates?  Maybe Jess can take a look too since she knows GIS and presumably has the software.

[EC_Summary_Apr2019.zip](https://github.com/r-b-g-b/clean-water-tool/files/3061234/EC_Summary_Apr2019.zip)

**Comment by r-b-g-b** [comment] 2019-04-10 05:44
That's awesome! Can you provide a link for where you got that zip file so we can add to the repo for the sake of reproducibility? @ruckeralex

**Comment by ruckeralex** [comment] 2019-04-10 17:42
Do we need the updated data each month?  I was hoping we can just use it this once to extract the georeference info for each of the public water systems, and then apply those coordinates to future months' data sets.  The georeference data should be based on centroid zip code.

I got the April file from the SWRCB staff-- the April file is not yet available on the website, but the Feb file is posted at this link: https://www.waterboards.ca.gov/water_issues/programs/hr2w/docs/data/ec_summary_feb2019.zip

There's no direct link to the page, but you can find it this way:
1) Go to https://www.waterboards.ca.gov/water_issues/programs/hr2w/#data 
2) Click on "Download GIS Map Shapefile"

**Comment by r-b-g-b** [comment] 2019-04-10 22:26
Great, yeah I wasn't thinking we'd update this each month. I just meant reproducibility in the sense that a future data scientist could clone this repo, do `make data` and have everything downloaded to a standard place and be ready to analyze.

**Comment by r-b-g-b** [comment] 2019-04-13 01:51
@ruckeralex Do you happen to know of a shapefile for the Tulare Lake Basin?

**Comment by ruckeralex** [comment] 2019-04-15 06:10
Yes, see attached for a zip file with about 6 different files for Tulare Lake Basin. 
[TLB_HUC06_TulareLakeBasin (1).zip](https://github.com/r-b-g-b/clean-water-tool/files/3078630/TLB_HUC06_TulareLakeBasin.1.zip)

**Comment by r-b-g-b** [comment] 2019-04-15 16:25
Thank you @ruckeralex ! Do you have a URL for that as well?

**Comment by ruckeralex** [comment] 2019-04-15 17:02
No. This was provided through the non-profit. 

Cheers,
Rucker

On Apr 15, 2019, at 9:25 AM, Robert Gibboni <notifications@github.com> wrote:

Thank you @ruckeralex ! Do you have a URL for that as well?

**Comment by r-b-g-b** [comment] 2019-04-15 17:17
Cool, is there any problem making this file publicly available? Then I can just add it directly to the repository. Thanks!

**Comment by ruckeralex** [comment] 2019-04-15 17:35
That should be fine. It’s not proprietary or confidential information (the “Basin” isn’t political boundary either; just a geographic designation to encompass many of the disadvantaged communities that the CWC targets for support.) 

Cheers,
Rucker

On Apr 15, 2019, at 10:17 AM, Robert Gibboni <notifications@github.com> wrote:

Cool, is there any problem making this file publicly available? Then I can just add it directly to the repository. Thanks!

**Comment by r-b-g-b** [comment] 2019-05-06 00:07
Closing since I think we have this covered!

**Closed as completed by r-b-g-b** 2019-05-06 00:07 UTC
